#!/usr/bin/env bash

set -e

# Get CWD

CWD=$PWD

# Get Script Directory

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "${DIR}"

BUILD_CACHE="$DIR/.rebuild"
CACHE_FILES="$DIR/Dockerfile"

if diff "${BUILD_CACHE}" <(stat -c "%Y" "${CACHE_FILES}" | tee "${BUILD_CACHE}") 1>/dev/null 2>/dev/null; then
  :
else
  docker build -t 'storj' "$DIR" || {
    rm "${BUILD_CACHE}";
    exit 1;
  }
fi

if [ -z "${STORJ_USER}" ]; then
  echo -e "\033[33mUsing default STORJ_USER: retrohacker\033[37m"
  STORJ_USER=retrohacker
fi

mkdir -p "${DIR}/${STORJ_USER}"

docker run \
  -it \
  -v "${DIR}/${STORJ_USER}:/home/foobar/.storjcli" \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  -e HOME=/home/foobar \
  -v "${CWD}:/usr/src/data" \
  --user $UID \
  --net host \
  storj "$@"
