#!/usr/bin/env bash

set -e

# Get CWD

CWD=$PWD

# Get Script Directory

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "${DIR}"

BUILD_CACHE="$DIR/.rebuild"
CACHE_FILES="$DIR/Dockerfile"

if diff "${BUILD_CACHE}" <(stat -c "%Y" "${CACHE_FILES}" | tee "${BUILD_CACHE}") 1>/dev/null 2>/dev/null; then
  :
else
  docker build -t 'heroku' "$DIR" || {
    rm "${BUILD_CACHE}";
    exit 1;
  }
fi

if [ -z "${HEROKU_USER}" ]; then
  echo -e "\033[33mUsing default HEROKU_USER: retrohacker\033[37m"
  HEROKU_USER=retrohacker
fi

mkdir -p "${DIR}/${HEROKU_USER}"

docker run -it \
  -v "${DIR}/${HEROKU_USER}:/root/" \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  -v "${CWD}:/usr/src/app" \
  heroku "$@"
