#!/usr/bin/env bash

set -e

CWD=${PWD}
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../build.sh ${BASH_SOURCE[0]}

if [ -z "${GH_USER}" ]; then
  GH_USER=retrohacker
fi

mkdir -p "${DIR}/${GH_USER}"

docker run -it \
  -v "${DIR}/${GH_USER}:/root" \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  --user $UID \
  -v "${CWD}:/usr/src/app" \
  exercism "$@"
