#!/usr/bin/env bash

set -e

CWD=${PWD}
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../build.sh ${BASH_SOURCE[0]}

docker run \
  -it \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  -v "${CWD}:/usr/src/data" \
  --workdir /usr/src/data \
  --net host \
  --user $UID \
  node "$@"
