#!/usr/bin/env bash

set -e

# Get CWD

CWD=$PWD

# Get Script Directory

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "${DIR}"

if [ -z "${NODE_VERSION}" ]; then
  echo -e "\033[33mUsing default NODE_VERSION: 6\033[37m"
  NODE_VERSION=6
fi

docker run \
  -it \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  -v "${CWD}:/usr/src/data" \
  --workdir /usr/src/data \
  --net host \
  --user $UID \
  --entrypoint node \
  node:$NODE_VERSION "$@"
