#!/usr/bin/env bash

set -e

# Get CWD

CWD=$PWD

# Get Script Directory

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "${DIR}"

BUILD_CACHE="$DIR/.rebuild"
CACHE_FILES="$DIR/Dockerfile"

if diff "${BUILD_CACHE}" <(stat -c "%Y" "${CACHE_FILES}" | tee "${BUILD_CACHE}") 1>/dev/null 2>/dev/null; then
  :
else
  docker build -t 'ws' "$DIR" || {
    rm "${BUILD_CACHE}";
    exit 1;
  }
fi

# Check for port
PORT=8000
while getopts ":p:" opt; do
  case $opt in
  p)
    PORT=$OPTARG
    ;;
  :)
    echo "Option -$OPTARG requires an argument." >&2
    exit 1
    ;;
  esac
done

if [ -n "$BACKGROUND" ]; then
  BACKGROUND="-d"
fi

docker run -it \
  --env-file <(env | grep -iv 'PATH=\|HOME=\|USER=') \
  -v "${CWD}:/usr/src/data" \
  -p "0.0.0.0:$PORT:$PORT" \
  $BACKGROUND \
  ws "$@"
